project_id = "pvxndzwaposcttrwkwgd"

[functions.translate-blog-post]
verify_jwt = true

[functions.generate-blog-content]
verify_jwt = true

[functions.generate-blog-image]
verify_jwt = true

[functions.generate-sitemap]
verify_jwt = false

[functions.analyze-blog-title]
verify_jwt = true

[functions.process-blog-queue]
verify_jwt = false